### PR TITLE
Externalize config

### PR DESCRIPTION
**Pull request by julian1**

### CODE REVIEW

**Comment by julian1** [comment]
ref https://github.com/aodn/geoserver-config/pull/262

**Comment by danfruehauf** [comment]
Looks good. I hope it works :)

**Comment by julian1** [comment]
@danfruehauf  Note, I've exposed the namespace as well as the layer in the http parameters.

So the synchronous-raw has another parameter, like this,

```
<wps:Input>
  <ows:Identifier>namespace</ows:Identifier>
  <wps:Data>
    <wps:LiteralData>imos</wps:LiteralData>
  </wps:Data>
</wps:Input>
```

**Comment by danfruehauf** [comment]
@julian1 I have updated the wps-evaluation repository with the correct values.

**Pull request merged**
