### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by dnahodil**

### CODE REVIEW

**Comment by julian1** [comment]
@dnahodil How do these changes affect the output of checkstyle? Eg. when running mvn checkstyle:checkstyle ?

**Comment by dnahodil** [comment]
92 errors, most of them from the RightCurly module. I'm not sure where that's defined but I reckon it's probably at odds with our code style. Reckon I should disable that module?

**Comment by julian1** [comment]
> I reckon it's probably at odds with our code style

It would be good to know why they conflict, and harmonize if possible. I'm inclined to trust checkstyle over 'our code style' unless there's a clear guidance from Oracle or some other source supporting our position.

**Comment by dnahodil** [comment]
Unless we configured checkstyle to match our chosen code styles then it is going to be wrong.

It seems that it wants this (which matches our chosen code style):

```
if (...) {
    // code
}
else {
    //more code
}
```

To be like this (which doesn't match our style):

```
if (...) {
    // code
} else { // <-- else on same line as right brace
    //more code
}
```

**Comment by julian1** [comment]
What is 'our style'? 

If there's no authority for it, other than it's what we randomly decided looked good, then I'd prefer to follow the conventions defined by the checkstyle plugin. 

Note that I originally coded it following our style. I then went back and manually changed it, to be conformant so it seems funny to have to revert this work.

**Comment by dnahodil** [comment]
We do have authority for it, @julian1. We have **a lot** of code which shows our preferred style. We have had discussions about many aspects of this (internal discussions and face-to-face) and have come to an agreement as a team. You used the key word there, it's a style we've _decided_ on.

I'm not saying that our style is necessarily better than theirs but it is the one we use and have agreed to. If you think we should change it you can bring it up in a discussion. But we aren't going to automatically change it just because some style checker has a different default to ours. I'm not sure why you changed work that matches our agreed style to not match it, that seems to make little sense.

**Comment by dnahodil** [comment]
I've updated the code style config to not have errors for these right braces.

We have a few options from here, @julian1.
If we want to use checkstyle for checking our code we need to:
- update the config to match our style, OR, we need to get agreement for the team to change our style
- integrate it into the build systems so that code style failures fail the build (same as we do for automated tests)
- get rid of the existing errors (which would now be failing the build)

I'll leave it up to you to decide if you'd like us to follow this any further. If you do then you can bring it up in an internal discussion or at a retro. In the meantime I would argue that it needn't hold this PR up.

How does that sound?

**Comment by julian1** [comment]
All the Google searches I do, indicate that Java convention favors the checkstyle plugin on this point. This includes Oracle's own documentation, at https://docs.oracle.com/javase/tutorial/java/nutsandbolts/if.html.

I acknowledge that if/else nesting rules in the style codeStyleSettings.xml do represent an IMOS coding convention. 

With that said, I can't find any examples specifically for Java. For example, the codeStyleSettings.xml in the aodn portal and gogo duck repos specify rules for groovy and javascript but are silent with respect to Java.  

I therefore don't believe there's evidence for any strong consensus amongst IMOS programmers on this issue. For the same reason, I doubt that following convention would substantially affect the code/ build processes of other projects.

It's pretty frustrating that after having made a substantial effort to correct style issues in this code-base, it appears we cannot in fact rely on standard tools used ubiquitously across the industry.

**Comment by dnahodil** [comment]
You're right in saying that the code style settings files in all our projects only refer to Groovy and Javascript. However, I would take from that just that they're the only languages we've bothered to set up style rules for because that's where most of our code is written. I took it as given that the same rules would apply to other c-style languages (including Java) unless we said otherwise.

So we have disagreement here about whether or not the styles rules for Groovy and Javascript would apply to a Java project. If we want to avoid this in the future then let's have an internal discussion or retro discussion so we're all on the same page.

Another discussion we might like to have is whether we want to include a code linter into our projects. If we do want to do that then we can either find one where we can configure rules to our liking, or we agree to change our standards.

**Comment by danfruehauf** [comment]
I'd like to see `else` clauses on the same line that the `}` appears. That's what most of the world does. Same with `try/catch`. I also don't like blank lines after function declarations, but that's another story.

However I'll have to side with @dnahodil on that. We're following arbitrary code conventions at IMOS. As much as they are arbitrary, lets stick with them because they are consistent.

**Comment by julian1** [comment]
@danfruehauf You're against idiomatic convention, to the extent that standard linters (that's what mvn checkstyle is) that can be run from the command line become worthless? And, instead we must rely on proprietary IDE code editors to enforce the rules?

**Comment by danfruehauf** [comment]
@julian1 In short - yes. Those are the IMOS conventions, lets follow them.

**Pull request merged**
