### PR TITLE
dumb down logic - support only async requests

### PR DESCRIPTION
**Pull request by danfruehauf**
- return a file when the process is done, no more streaming
- use ProgressListener to identify process termination and cancel

### CODE REVIEW

**Comment by julian1** [comment]
@danfruehauf  does this work for synchronous as well? For example does the ProgressListener correctly interupt the main loop if the http-client breaks off a connection?

**Comment by danfruehauf** [comment]
@julian1 No - and that is I think a geoserver bug, yet I'm not sure. We need to further investigate how geoserver signals a GSProcess that a client has disconnected when in sync mode...

**Comment by julian1** [comment]
@danfruehauf I'll merge this if you want - in order to have something in production/systest that is acceptable contractually. We can continue to work on a better solution independently.

**Comment by danfruehauf** [comment]
I'll just have to rebase after your changes...

And sorry for removing the bulk of your code. TBH I think this code should be part of the WPS infrastructure geoserver provides. Don't you think?

**Comment by danfruehauf** [comment]
Should be GTG.

**Pull request merged**
