### PR TITLE
Allow equality operator in valid cql passed to parser

### PR DESCRIPTION
**Pull request by anguss00**

### CODE REVIEW

**Comment by julian1** [comment]
@anguss00  have we got a cql not operator as well?

**Comment by anguss00** [comment]
I think the operator != is not supported by CQL, see http://cassandra.apache.org/doc/cql/CQL.html#SELECT

**Comment by julian1** [comment]
Is Common Query Language the same as Cassandra (the db) Query Language?

**Comment by anguss00** [comment]
Sorry yeah, they're not necessarily the same... In the CQL reference for geoserver here http://docs.geoserver.org/2.6.x/en/user/filter/ecql_reference.html#filter-ecql-reference they don't list != as a comparison operator but they list NOT as a potential operator. Do we currently handle NOT?

**Pull request closed without merging**
