### PR TITLE
Package template in the jar

### PR DESCRIPTION
**Pull request by jkburges**
This is to ease deployment (of templates) to production, although it's likely they might end up living and being managed from somewhere else in the long run.

### CODE REVIEW

**Comment by julian1** [comment]
Do the itnegration tests still run when these are moved to this subfolder?

**Comment by jkburges** [comment]
I tested `mvn test` - which works.

**Comment by julian1** [comment]
what does,

mvn -Dtest=GenerationIT#anmn_timeseries_gg_IT    test

do?

**Comment by julian1** [comment]
I mean,

mvn -Dtest=GenerationIT#anmn_timeseries_IT    test

**Comment by julian1** [comment]
mvn test will only run units at the moment.

**Comment by jkburges** [comment]
Ok, I'll check.

**Comment by jkburges** [comment]
`mvn -Dtest=MyIT#anmn_timeseries_IT   test` passes (assuming that's the correct test).
`mvn -Dtest=MyIT test` does not (but it does not on master either): see https://gist.github.com/jkburges/9ea0c175b6850db30436

**Comment by julian1** [comment]
Ok, I'll wait to merge this, because there are new files in current code that will need to move too.

**Comment by julian1** [comment]
Addressed here, https://github.com/aodn/ncdfgenerator/pull/13

**Pull request closed without merging**
