### PR TITLE
Remove final modifier of write() method 

### PR DESCRIPTION
**Pull request by dnahodil**
It was preventing mocking from working properly in testing (NetCDF subset service project)

### CODE REVIEW

**Comment by julian1** [comment]
does it deserve a comment indicating the reason?

**Comment by dnahodil** [comment]
A comment in the code?

**Comment by dnahodil** [comment]
To prevent anyone making it final again?

**Comment by julian1** [comment]
Yes. since it's a bit of an exception. I don't mind one way or the other.

**Comment by dnahodil** [comment]
I'll drop one in.

**Pull request merged**
